BEGIN ;
SELECT * FROM t WHERE id = 9 FOR UPDATE ;
SELECT trx_id, trx_mysql_thread_id FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = CONNECTION_ID();
# 2337,10
SELECT ENGINE_TRANSACTION_ID, INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS, LOCK_DATA
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'test' AND OBJECT_NAME = 't';
# 2337,,TABLE,IX,GRANTED,
# 2337,PRIMARY,RECORD,"X,GAP",GRANTED,10
# switch to session 2
SELECT ENGINE_TRANSACTION_ID, INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS, LOCK_DATA
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'test' AND OBJECT_NAME = 't';
# 2338,,TABLE,IX,GRANTED,
# 2338,PRIMARY,RECORD,"X,GAP",GRANTED,10
# 2338,PRIMARY,RECORD,"X,GAP,INSERT_INTENTION",WAITING,10
# 2337,,TABLE,IX,GRANTED,
# 2337,PRIMARY,RECORD,"X,GAP",GRANTED,10
INSERT INTO t VALUES (9, 9, 9);
# [40001][1213] Deadlock found when trying to get lock; try restarting transaction
# session 2 is unblocked
SELECT ENGINE_TRANSACTION_ID, INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS, LOCK_DATA
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'test' AND OBJECT_NAME = 't';
# 2338,,TABLE,IX,GRANTED,
# 2338,PRIMARY,RECORD,"X,GAP",GRANTED,10
# 2338,PRIMARY,RECORD,"X,GAP",GRANTED,9
# 2338,PRIMARY,RECORD,"X,GAP,INSERT_INTENTION",GRANTED,10
# switch to session 2
ROLLBACK ;