CREATE TABLE `t`
(
    `ftime` DATETIME NOT NULL,
    `c`     INT(11) DEFAULT NULL,
    KEY (`ftime`)
) ENGINE = InnoDB
  DEFAULT CHARSET = latin1
    PARTITION BY RANGE (YEAR(ftime))
        (PARTITION p_2017 VALUES LESS THAN (2017) ENGINE = InnoDB,
        PARTITION p_2018 VALUES LESS THAN (2018) ENGINE = InnoDB,
        PARTITION p_2019 VALUES LESS THAN (2019) ENGINE = InnoDB,
        PARTITION p_others VALUES LESS THAN MAXVALUE ENGINE = InnoDB);
INSERT INTO t
VALUES ('2017-4-1', 1),
       ('2018-4-1', 1);