BEGIN ;
SELECT ENGINE_TRANSACTION_ID, INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS, LOCK_DATA
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'test' AND OBJECT_NAME = 't' AND INDEX_NAME = 'c';
# 2328,c,RECORD,"X,GAP,INSERT_INTENTION",WAITING,"15, 15"
# 2327,c,RECORD,"X,GAP",GRANTED,"25, 25"
# 2327,c,RECORD,X,GRANTED,"10, 10"
# 2327,c,RECORD,X,GRANTED,"15, 15"
# 2327,c,RECORD,X,GRANTED,"20, 20"
SELECT REQUESTING_ENGINE_TRANSACTION_ID, BLOCKING_ENGINE_TRANSACTION_ID FROM performance_schema.data_lock_waits;
# 2328,2327
INSERT INTO t VALUES (6, 6, 6);
# blocked
# switch to session 1
ROLLBACK ;