BEGIN ;
SELECT * FROM t WHERE c >= 15 AND c <= 20 ORDER BY c DESC FOR UPDATE ;
SELECT trx_id, trx_mysql_thread_id FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = CONNECTION_ID();
# 2327,11
SELECT ENGINE_TRANSACTION_ID, INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS, LOCK_DATA
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'test' AND OBJECT_NAME = 't' AND INDEX_NAME = 'c';
# 2327,c,RECORD,"X,GAP",GRANTED,"25, 25"
# 2327,c,RECORD,X,GRANTED,"10, 10"
# 2327,c,RECORD,X,GRANTED,"15, 15"
# 2327,c,RECORD,X,GRANTED,"20, 20"
SELECT REQUESTING_ENGINE_TRANSACTION_ID, BLOCKING_ENGINE_TRANSACTION_ID FROM performance_schema.data_lock_waits;
# switch to session 2
SELECT ENGINE_TRANSACTION_ID, INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS, LOCK_DATA
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'test' AND OBJECT_NAME = 't' AND INDEX_NAME = 'c';
# 2329,c,RECORD,"X,GAP,INSERT_INTENTION",WAITING,"10, 10"
# 2328,c,RECORD,"X,GAP,INSERT_INTENTION",WAITING,"15, 15"
# 2327,c,RECORD,"X,GAP",GRANTED,"25, 25"
# 2327,c,RECORD,X,GRANTED,"10, 10"
# 2327,c,RECORD,X,GRANTED,"15, 15"
# 2327,c,RECORD,X,GRANTED,"20, 20"
SELECT REQUESTING_ENGINE_TRANSACTION_ID, BLOCKING_ENGINE_TRANSACTION_ID FROM performance_schema.data_lock_waits;
# 2329,2327
# 2328,2327
ROLLBACK ;