BEGIN ;
SELECT * FROM t WHERE d = 5 for UPDATE ;
# result: (5, 5, 5)
SELECT INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS, LOCK_DATA
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'test' AND OBJECT_NAME = 't';
# <null>,TABLE,IX,GRANTED,<null>
# PRIMARY,RECORD,X,GRANTED,supremum pseudo-record
# PRIMARY,RECORD,X,GRANTED,0
# PRIMARY,RECORD,X,GRANTED,5
# PRIMARY,RECORD,X,GRANTED,10
# PRIMARY,RECORD,X,GRANTED,15
# PRIMARY,RECORD,X,GRANTED,20
# PRIMARY,RECORD,X,GRANTED,25
# d 上没有索引，所以会按主键全表扫描。间隙锁升级为表锁：<null>,TABLE,IX,GRANTED,<null>
COMMIT ;