INSERT INTO t VALUES(30,10,30);
BEGIN ;
DELETE FROM t WHERE c = 10 ;
SELECT trx_id, trx_mysql_thread_id FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = CONNECTION_ID();
# 2323,8
SELECT ENGINE_TRANSACTION_ID, INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS, LOCK_DATA
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'test' AND OBJECT_NAME = 't';
# 2323,,TABLE,IX,GRANTED,
# 2323,c,RECORD,X,GRANTED,"10, 10"
# 2323,c,RECORD,X,GRANTED,"10, 30"
# 2323,PRIMARY,RECORD,"X,REC_NOT_GAP",GRANTED,10
# 2323,PRIMARY,RECORD,"X,REC_NOT_GAP",GRANTED,30
# 2323,c,RECORD,"X,GAP",GRANTED,"15, 15"
# switch to session 2
SELECT ENGINE_TRANSACTION_ID, INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS, LOCK_DATA
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'test' AND OBJECT_NAME = 't';
# 2328,,TABLE,IX,GRANTED,
# 2328,c,RECORD,"X,GAP,INSERT_INTENTION",WAITING,"15, 15"
# 2323,,TABLE,IX,GRANTED,
# 2323,c,RECORD,X,GRANTED,"10, 10"
# 2323,c,RECORD,X,GRANTED,"10, 30"
# 2323,PRIMARY,RECORD,"X,REC_NOT_GAP",GRANTED,10
# 2323,PRIMARY,RECORD,"X,REC_NOT_GAP",GRANTED,30
# 2323,c,RECORD,"X,GAP",GRANTED,"15, 15"
ROLLBACK ;
