call idata();
--
SET GLOBAL SLOW_QUERY_LOG = 'ON';
SET LONG_QUERY_TIME = 0;
SHOW VARIABLES LIKE '%SLOW_QUERY%';
SHOW VARIABLES LIKE '%LONG_QUERY%';
FLUSH TABLES t;
SELECT * FROM t WHERE c = 50000 LIMIT 1;
# slow query log: Query_time: 0.021979  Lock_time: 0.000004 Rows_sent: 1  Rows_examined: 50000
--
START TRANSACTION WITH CONSISTENT SNAPSHOT ;
# switch to session 2
SELECT * FROM t WHERE id = 1;
SELECT * FROM t WHERE id = 1 LOCK IN SHARE MODE ;