BEGIN ;
SELECT * FROM t WHERE id = 10 FOR UPDATE ;
SELECT trx_id, trx_mysql_thread_id FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = CONNECTION_ID();
# 2321,11
SELECT ENGINE_TRANSACTION_ID, INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS, LOCK_DATA
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'test' AND OBJECT_NAME = 't';
# 2321,,TABLE,IX,GRANTED,
# 2321,PRIMARY,RECORD,"X,REC_NOT_GAP",GRANTED,10
ROLLBACK ;
BEGIN ;
SELECT * FROM t WHERE id >= 10 AND id < 11 FOR UPDATE ;
SELECT trx_id, trx_mysql_thread_id FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = CONNECTION_ID();
# 2322,11
SELECT ENGINE_TRANSACTION_ID, INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS, LOCK_DATA
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'test' AND OBJECT_NAME = 't';
# 2322,,TABLE,IX,GRANTED,
# 2322,PRIMARY,RECORD,"X,REC_NOT_GAP",GRANTED,10
# 2322,PRIMARY,RECORD,"X,GAP",GRANTED,15
ROLLBACK ;
--
BEGIN ;
SELECT * FROM t WHERE id >= 10 AND id < 11 FOR UPDATE ;
# switch to session 2

SELECT trx_id, trx_mysql_thread_id FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = CONNECTION_ID();
# 2323,11
SELECT ENGINE_TRANSACTION_ID, INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS, LOCK_DATA
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'test' AND OBJECT_NAME = 't';
# 2331,,TABLE,IX,GRANTED,
# 2331,PRIMARY,RECORD,"X,GAP,INSERT_INTENTION",WAITING,15
# 2323,,TABLE,IX,GRANTED,
# 2323,PRIMARY,RECORD,"X,REC_NOT_GAP",GRANTED,10
# 2323,PRIMARY,RECORD,"X,GAP",GRANTED,15
SELECT REQUESTING_ENGINE_TRANSACTION_ID, BLOCKING_ENGINE_TRANSACTION_ID FROM performance_schema.data_lock_waits;
# 2331,2323
ROLLBACK ;
