INSERT INTO t VALUES(30,10,30);
BEGIN ;
DELETE FROM t WHERE c = 10 LIMIT 2;
SELECT trx_id, trx_mysql_thread_id FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = CONNECTION_ID();
# 2324,10
SELECT ENGINE_TRANSACTION_ID, INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS, LOCK_DATA
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'test' AND OBJECT_NAME = 't';
# 2324,,TABLE,IX,GRANTED,
# 2324,c,RECORD,X,GRANTED,"10, 10"
# 2324,c,RECORD,X,GRANTED,"10, 30"
# 2324,PRIMARY,RECORD,"X,REC_NOT_GAP",GRANTED,10
# 2324,PRIMARY,RECORD,"X,REC_NOT_GAP",GRANTED,30
# switch to session 2
ROLLBACK ;
