version: "3.9"
name: ch21_case5
services:
  mysqld:
#    image: bitnami/mysql:8.0.39
#    image: bitnami/mysql:8.4.3
    image: bitnami/mysql:9.0.1
    restart: always
    volumes:
      - ./db_init.d:/docker-entrypoint-initdb.d
      - ./conf/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: sa_pass
      MYSQL_DATABASE: test
    ports:
      - "3306"