BEGIN ;
SELECT * FROM t WHERE c >= 10 AND c < 11 FOR UPDATE ;
SELECT trx_id, trx_mysql_thread_id FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = CONNECTION_ID();
# 2321,10
SELECT ENGINE_TRANSACTION_ID, INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS, LOCK_DATA
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'test' AND OBJECT_NAME = 't';
# 2321,,TABLE,IX,GRANTED,
# 2321,c,RECORD,X,GRANTED,"10, 10"
# 2321,c,RECORD,X,GRANTED,"15, 15"
# 2321,PRIMARY,RECORD,"X,REC_NOT_GAP",GRANTED,10
# switch to session 2
SELECT ENGINE_TRANSACTION_ID, INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS, LOCK_DATA
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'test' AND OBJECT_NAME = 't';
# 2327,,TABLE,IX,GRANTED,
# 2327,c,RECORD,X,WAITING,"15, 15"
# 2326,,TABLE,IX,GRANTED,
# 2326,c,RECORD,"X,GAP,INSERT_INTENTION",WAITING,"10, 10"
# 2321,,TABLE,IX,GRANTED,
# 2321,c,RECORD,X,GRANTED,"10, 10"
# 2321,c,RECORD,X,GRANTED,"15, 15"
# 2321,PRIMARY,RECORD,"X,REC_NOT_GAP",GRANTED,10
ROLLBACK ;
